@TodoApi_HostAddress = https://localhost:7136

GET {{TodoApi_HostAddress}}/api/todoitems
Accept: application/json

###

POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###

@id=1
GET {{TodoApi_HostAddress}}/api/todoitems/{{id}}

###

